/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conversion;

import calculations.Others;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author eljon
 */
public class Temperature extends javax.swing.JFrame {

    /**
     * Creates new form Tempt
     */
    public Temperature() {
        initComponents();
        
        Image icon = new ImageIcon(this.getClass().getResource("icons8_math_50px.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbt_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tempt = new javax.swing.JTextField();
        jCB1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCB2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton_Convert = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Conversion");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jbt_back.setBackground(new java.awt.Color(0, 0, 0));
        jbt_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_left_arrow_32px.png"))); // NOI18N
        jbt_back.setBorder(null);
        jbt_back.setBorderPainted(false);
        jbt_back.setContentAreaFilled(false);
        jbt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_backActionPerformed(evt);
            }
        });
        jPanel3.add(jbt_back);
        jbt_back.setBounds(0, 0, 32, 32);

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 255, 212));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_temperature_24px.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 20, 24, 24);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEMPERATURE");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(110, 20, 100, 30);

        tempt.setBackground(new java.awt.Color(49, 104, 91));
        tempt.setForeground(new java.awt.Color(255, 255, 255));
        tempt.setBorder(null);
        tempt.setOpaque(true);
        tempt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temptActionPerformed(evt);
            }
        });
        jPanel3.add(tempt);
        tempt.setBounds(40, 80, 100, 50);

        jCB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCB1.setForeground(new java.awt.Color(0, 208, 201));
        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin" }));
        jCB1.setBorder(null);
        jCB1.setFocusable(false);
        jPanel3.add(jCB1);
        jCB1.setBounds(190, 80, 92, 50);

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(40, 140, 99, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcis/gradient(2).png"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 310, 190);

        jPanel4.setBackground(new java.awt.Color(32, 70, 61));

        jCB2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCB2.setForeground(new java.awt.Color(0, 208, 201));
        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Kelvin" }));
        jCB2.setBorder(null);
        jCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB2ActionPerformed(evt);
            }
        });

        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 184, 184), 1, true));
        jTextField2.setOpaque(true);

        jButton_Convert.setText("Convert");
        jButton_Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConvertActionPerformed(evt);
            }
        });

        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jButton_Convert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Clear)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Clear)
                    .addComponent(jButton_Convert))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(324, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void temptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temptActionPerformed

    private void jCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB2ActionPerformed

    private void jButton_ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConvertActionPerformed
        String box1 = (String)jCB1.getSelectedItem();
        String box2 = (String)jCB2.getSelectedItem();
        
            if(box1.equals("Celcius") && box2.equals("Fahrenheit")){
                double Celcius = Double.parseDouble(tempt.getText());
                
                double Fahrenheit = (double)(Celcius*1.8 + 32);
                
                jTextField2.setText(String.valueOf(Fahrenheit));
            }
            
            else if(box1.equals("Celcius") && box2.equals("Kelvin")){
                double Celcius = Double.parseDouble(tempt.getText());
                
                double Kelvin = (double)(Celcius + 273.15);
                
                jTextField2.setText(String.valueOf(Kelvin));
            }
            else if(box1.equals("Celcius") && box2.equals("Celcius")){
                double Celcius = Double.parseDouble(tempt.getText());
                jTextField2.setText(String.valueOf(Celcius));
            }
            
            
//Fahrenheit        
            
            if(box1.equals("Fahrenheit") && box2.equals("Celcius")){
                double Fahrenheit = Double.parseDouble(tempt.getText());
                
                double Celcius = (double)((Fahrenheit - 32)*5/9);
                
                jTextField2.setText(String.valueOf(Celcius));
            }
            
            else if(box1.equals("Fahrenheit") && box2.equals("Kelvin")){
                double Fahrenheit = Double.parseDouble(tempt.getText());
                
                double Kelvin = (double)((Fahrenheit - 32)*5/9 + 273.15);
                
                jTextField2.setText(String.valueOf(Kelvin));
            }
            else if(box1.equals("Fahrenheit") && box2.equals("Fahrenheit")){
                double Fahrenheit = Double.parseDouble(tempt.getText());
                jTextField2.setText(String.valueOf(Fahrenheit));
            }
            
            
//Kelvin        
            
            if(box1.equals("Kelvin") && box2.equals("Celcius")){
                double Kelvin = Double.parseDouble(tempt.getText());
                
                double Celcius = (double)(Kelvin - 273.15);
                
                jTextField2.setText(String.valueOf(Celcius));
            }
            
            else if(box1.equals("Kelvin") && box2.equals("Fahrenheit")){
                double Kelvin = Double.parseDouble(tempt.getText());
                
                double Fahrenheit = (double)((Kelvin - 273.15) * 9/5 +32);
                
                jTextField2.setText(String.valueOf(Fahrenheit));
            }
            else if(box1.equals("Kelvin") && box2.equals("Kelvin")){
                double Kelvin = Double.parseDouble(tempt.getText());
                jTextField2.setText(String.valueOf(Kelvin));
            }
    }//GEN-LAST:event_jButton_ConvertActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        tempt.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jbt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_backActionPerformed
        Others others = new Others();
        others.show();

        dispose();
    }//GEN-LAST:event_jbt_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperature().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Convert;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbt_back;
    private javax.swing.JTextField tempt;
    // End of variables declaration//GEN-END:variables
}
