/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculations;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author eljon
 */
public class Calc extends javax.swing.JFrame {

    double fnum;
    double snum;
    double result;
    String operator;
    
    public Calc() {
        initComponents();
        
        
        //!!!icon needs to be on the same package
        //change java icon
        Image icon = new ImageIcon(this.getClass().getResource("icons8_math_50px.png")).getImage();
        this.setIconImage(icon);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_result = new javax.swing.JLabel();
        JB_CE = new javax.swing.JButton();
        JB_Modulus = new javax.swing.JButton();
        JB_C = new javax.swing.JButton();
        JB_divide = new javax.swing.JButton();
        JB_8 = new javax.swing.JButton();
        JB_7 = new javax.swing.JButton();
        JB_9 = new javax.swing.JButton();
        JB_multiply = new javax.swing.JButton();
        JB_5 = new javax.swing.JButton();
        JB_4 = new javax.swing.JButton();
        JB_6 = new javax.swing.JButton();
        JB__subtract = new javax.swing.JButton();
        JB_2 = new javax.swing.JButton();
        JB_1 = new javax.swing.JButton();
        JB_3 = new javax.swing.JButton();
        JB__add = new javax.swing.JButton();
        JB_00 = new javax.swing.JButton();
        JB_0 = new javax.swing.JButton();
        JB__dot = new javax.swing.JButton();
        JB_equals = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        jPanel1.setBackground(new java.awt.Color(7, 7, 7));
        jPanel1.setForeground(new java.awt.Color(7, 7, 7));

        jLabel_result.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_result.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        jLabel_result.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_result.setToolTipText("");
        jLabel_result.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel_result.setOpaque(true);
        jLabel_result.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        JB_CE.setBackground(new java.awt.Color(0, 0, 0));
        JB_CE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_CE.setForeground(new java.awt.Color(0, 208, 201));
        JB_CE.setText("CE");
        JB_CE.setBorder(null);
        JB_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CEActionPerformed(evt);
            }
        });

        JB_Modulus.setBackground(new java.awt.Color(0, 0, 0));
        JB_Modulus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_Modulus.setForeground(new java.awt.Color(0, 208, 201));
        JB_Modulus.setText("%");
        JB_Modulus.setBorder(null);
        JB_Modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ModulusActionPerformed(evt);
            }
        });

        JB_C.setBackground(new java.awt.Color(0, 0, 0));
        JB_C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_C.setForeground(new java.awt.Color(0, 208, 201));
        JB_C.setText("C");
        JB_C.setBorder(null);
        JB_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CActionPerformed(evt);
            }
        });

        JB_divide.setBackground(new java.awt.Color(0, 0, 0));
        JB_divide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_divide.setForeground(new java.awt.Color(0, 208, 201));
        JB_divide.setText("÷");
        JB_divide.setBorder(null);
        JB_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_divideActionPerformed(evt);
            }
        });

        JB_8.setBackground(new java.awt.Color(0, 0, 0));
        JB_8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_8.setForeground(new java.awt.Color(255, 255, 255));
        JB_8.setText("8");
        JB_8.setBorder(null);
        JB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_8ActionPerformed(evt);
            }
        });

        JB_7.setBackground(new java.awt.Color(0, 0, 0));
        JB_7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_7.setForeground(new java.awt.Color(255, 255, 255));
        JB_7.setText("7");
        JB_7.setBorder(null);
        JB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_7ActionPerformed(evt);
            }
        });

        JB_9.setBackground(new java.awt.Color(0, 0, 0));
        JB_9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_9.setForeground(new java.awt.Color(255, 255, 255));
        JB_9.setText("9");
        JB_9.setBorder(null);
        JB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_9ActionPerformed(evt);
            }
        });

        JB_multiply.setBackground(new java.awt.Color(0, 0, 0));
        JB_multiply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_multiply.setForeground(new java.awt.Color(0, 208, 201));
        JB_multiply.setText("x");
        JB_multiply.setBorder(null);
        JB_multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_multiplyActionPerformed(evt);
            }
        });

        JB_5.setBackground(new java.awt.Color(0, 0, 0));
        JB_5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_5.setForeground(new java.awt.Color(255, 255, 255));
        JB_5.setText("5");
        JB_5.setBorder(null);
        JB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_5ActionPerformed(evt);
            }
        });

        JB_4.setBackground(new java.awt.Color(0, 0, 0));
        JB_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_4.setForeground(new java.awt.Color(255, 255, 255));
        JB_4.setText("4");
        JB_4.setBorder(null);
        JB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_4ActionPerformed(evt);
            }
        });

        JB_6.setBackground(new java.awt.Color(0, 0, 0));
        JB_6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_6.setForeground(new java.awt.Color(255, 255, 255));
        JB_6.setText("6");
        JB_6.setBorder(null);
        JB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_6ActionPerformed(evt);
            }
        });

        JB__subtract.setBackground(new java.awt.Color(0, 0, 0));
        JB__subtract.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB__subtract.setForeground(new java.awt.Color(0, 208, 201));
        JB__subtract.setText("-");
        JB__subtract.setBorder(null);
        JB__subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB__subtractActionPerformed(evt);
            }
        });

        JB_2.setBackground(new java.awt.Color(0, 0, 0));
        JB_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_2.setForeground(new java.awt.Color(255, 255, 255));
        JB_2.setText("2");
        JB_2.setBorder(null);
        JB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_2ActionPerformed(evt);
            }
        });

        JB_1.setBackground(new java.awt.Color(0, 0, 0));
        JB_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_1.setForeground(new java.awt.Color(255, 255, 255));
        JB_1.setText("1");
        JB_1.setBorder(null);
        JB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_1ActionPerformed(evt);
            }
        });

        JB_3.setBackground(new java.awt.Color(0, 0, 0));
        JB_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_3.setForeground(new java.awt.Color(255, 255, 255));
        JB_3.setText("3");
        JB_3.setBorder(null);
        JB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_3ActionPerformed(evt);
            }
        });

        JB__add.setBackground(new java.awt.Color(0, 0, 0));
        JB__add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB__add.setForeground(new java.awt.Color(0, 208, 201));
        JB__add.setText("+");
        JB__add.setBorder(null);
        JB__add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB__addActionPerformed(evt);
            }
        });

        JB_00.setBackground(new java.awt.Color(0, 0, 0));
        JB_00.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_00.setForeground(new java.awt.Color(255, 255, 255));
        JB_00.setText("00");
        JB_00.setBorder(null);
        JB_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_00ActionPerformed(evt);
            }
        });

        JB_0.setBackground(new java.awt.Color(0, 0, 0));
        JB_0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_0.setForeground(new java.awt.Color(255, 255, 255));
        JB_0.setText("0");
        JB_0.setBorder(null);
        JB_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_0ActionPerformed(evt);
            }
        });

        JB__dot.setBackground(new java.awt.Color(0, 0, 0));
        JB__dot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB__dot.setForeground(new java.awt.Color(255, 255, 255));
        JB__dot.setText(".");
        JB__dot.setBorder(null);
        JB__dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB__dotActionPerformed(evt);
            }
        });

        JB_equals.setBackground(new java.awt.Color(0, 0, 0));
        JB_equals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JB_equals.setForeground(new java.awt.Color(0, 208, 201));
        JB_equals.setText("=");
        JB_equals.setBorder(null);
        JB_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_equalsActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_four_squares_24px_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_Modulus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_C, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB__subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB__add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_00, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB__dot, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_result, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Modulus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_C, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB__subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB__add, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_00, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB__dot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void EnterNumbers(String a){
        String number = jLabel_result.getText() + a;
        jLabel_result.setText(number);
    }
    
    private void JB_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CEActionPerformed

       String del = null;
       
       if(jLabel_result.getText().length() > 0){
           StringBuilder sb = new StringBuilder(jLabel_result.getText());
           sb.deleteCharAt(jLabel_result.getText().length() - 1);
           del = sb.toString();
           jLabel_result.setText(del);
       }
    }//GEN-LAST:event_JB_CEActionPerformed

    private void JB_ModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ModulusActionPerformed
       fnum = Double.parseDouble(jLabel_result.getText());
        jLabel_result.setText("");
        operator = "%";
    }//GEN-LAST:event_JB_ModulusActionPerformed

    private void JB_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CActionPerformed
       jLabel_result.setText("");
    }//GEN-LAST:event_JB_CActionPerformed

    private void JB_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_divideActionPerformed
        fnum = Double.parseDouble(jLabel_result.getText());
        jLabel_result.setText("");
        operator = "÷";
    }//GEN-LAST:event_JB_divideActionPerformed

    private void JB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_JB_8ActionPerformed

    private void JB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_JB_7ActionPerformed

    private void JB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_JB_9ActionPerformed

    private void JB_multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_multiplyActionPerformed
        fnum = Double.parseDouble(jLabel_result.getText());
        jLabel_result.setText("");
        operator = "x";
    }//GEN-LAST:event_JB_multiplyActionPerformed

    private void JB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_JB_5ActionPerformed

    private void JB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_4ActionPerformed
       EnterNumbers("4");
    }//GEN-LAST:event_JB_4ActionPerformed

    private void JB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_JB_6ActionPerformed

    private void JB__subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB__subtractActionPerformed
        fnum = Double.parseDouble(jLabel_result.getText());
        jLabel_result.setText("");
        operator = "-";
    }//GEN-LAST:event_JB__subtractActionPerformed

    private void JB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_JB_2ActionPerformed

    private void JB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_JB_1ActionPerformed

    private void JB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_JB_3ActionPerformed

    private void JB__addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB__addActionPerformed
        fnum = Double.parseDouble(jLabel_result.getText());
        jLabel_result.setText("");
        operator = "+";
    }//GEN-LAST:event_JB__addActionPerformed

    private void JB_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_00ActionPerformed
        EnterNumbers("00");
    }//GEN-LAST:event_JB_00ActionPerformed

    private void JB_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_JB_0ActionPerformed

    private void JB__dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB__dotActionPerformed
       if(!jLabel_result.getText().contains(".")){
           jLabel_result.setText(jLabel_result.getText() + JB__dot.getText());
       }
    }//GEN-LAST:event_JB__dotActionPerformed

    private void JB_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_equalsActionPerformed
       snum = Double.parseDouble(jLabel_result.getText());
       
       if(operator == "+"){
           result = fnum + snum;
           jLabel_result.setText(String.valueOf(result));
       }
       
       else if(operator == "-"){
           result = fnum - snum;
           jLabel_result.setText(String.valueOf(result));
       }
       
       else if(operator == "x"){
           result = fnum * snum;
           jLabel_result.setText(String.valueOf(result));
       }
       
       else if(operator == "÷"){
           result = fnum / snum;
           jLabel_result.setText(String.valueOf(result));
       }
       
        else if(operator == "%"){
           result = fnum % snum;
           jLabel_result.setText(String.valueOf(result));
       }
    }//GEN-LAST:event_JB_equalsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Others others = new Others();
        others.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_0;
    private javax.swing.JButton JB_00;
    private javax.swing.JButton JB_1;
    private javax.swing.JButton JB_2;
    private javax.swing.JButton JB_3;
    private javax.swing.JButton JB_4;
    private javax.swing.JButton JB_5;
    private javax.swing.JButton JB_6;
    private javax.swing.JButton JB_7;
    private javax.swing.JButton JB_8;
    private javax.swing.JButton JB_9;
    private javax.swing.JButton JB_C;
    private javax.swing.JButton JB_CE;
    private javax.swing.JButton JB_Modulus;
    private javax.swing.JButton JB__add;
    private javax.swing.JButton JB__dot;
    private javax.swing.JButton JB__subtract;
    private javax.swing.JButton JB_divide;
    private javax.swing.JButton JB_equals;
    private javax.swing.JButton JB_multiply;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_result;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
