/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculations;

import Conversion.Length;
import Conversion.Temperature;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author eljon
 */
public class Others extends javax.swing.JFrame {

    /**
     * Creates new form Others1
     */
    public Others() {
        initComponents();
        
        Image icon = new ImageIcon(this.getClass().getResource("icons8_math_50px.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbt_length = new javax.swing.JButton();
        jbt_weight = new javax.swing.JButton();
        jbt_tempearture = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbt_length1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversion Units");

        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_left_arrow_32px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 32, 32);

        jbt_length.setBackground(new java.awt.Color(0, 0, 0));
        jbt_length.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_length_26px.png"))); // NOI18N
        jbt_length.setBorder(null);
        jbt_length.setBorderPainted(false);
        jbt_length.setContentAreaFilled(false);
        jbt_length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_lengthActionPerformed(evt);
            }
        });
        jPanel1.add(jbt_length);
        jbt_length.setBounds(50, 85, 26, 26);

        jbt_weight.setBackground(new java.awt.Color(0, 0, 0));
        jbt_weight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_weight_32px_1.png"))); // NOI18N
        jbt_weight.setBorder(null);
        jbt_weight.setBorderPainted(false);
        jbt_weight.setContentAreaFilled(false);
        jPanel1.add(jbt_weight);
        jbt_weight.setBounds(135, 80, 32, 32);

        jbt_tempearture.setBackground(new java.awt.Color(0, 0, 0));
        jbt_tempearture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_temperature_24px.png"))); // NOI18N
        jbt_tempearture.setBorder(null);
        jbt_tempearture.setBorderPainted(false);
        jbt_tempearture.setContentAreaFilled(false);
        jbt_tempearture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_tempeartureActionPerformed(evt);
            }
        });
        jPanel1.add(jbt_tempearture);
        jbt_tempearture.setBounds(220, 87, 24, 24);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 208, 201));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LENGTH");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 120, 60, 14);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 208, 201));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WEIGHT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 120, 60, 14);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 208, 201));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TEMPERATURE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(193, 120, 80, 14);

        jbt_length1.setBackground(new java.awt.Color(0, 0, 0));
        jbt_length1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Us_Dollar_Circled_24px.png"))); // NOI18N
        jbt_length1.setBorder(null);
        jbt_length1.setBorderPainted(false);
        jbt_length1.setContentAreaFilled(false);
        jPanel1.add(jbt_length1);
        jbt_length1.setBounds(50, 170, 24, 24);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 208, 201));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CURRENCY");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(34, 210, 60, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcis/gradient(2).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 856, 1319);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(324, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Calc calc = new Calc();
        calc.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbt_lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_lengthActionPerformed
        Length length = new Length();
        length.show();

        dispose();
    }//GEN-LAST:event_jbt_lengthActionPerformed

    private void jbt_tempeartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_tempeartureActionPerformed
         Temperature temp = new Temperature();
        temp.show();

        dispose();
    }//GEN-LAST:event_jbt_tempeartureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Others().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbt_length;
    private javax.swing.JButton jbt_length1;
    private javax.swing.JButton jbt_tempearture;
    private javax.swing.JButton jbt_weight;
    // End of variables declaration//GEN-END:variables
}
